# Generated by Django 3.1.4 on 2021-02-19 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_no', models.IntegerField()),
                ('model_name', models.CharField(max_length=30)),
                ('feature', models.CharField(max_length=30)),
                ('Contact', models.CharField(max_length=30)),
                ('Photo', models.CharField(max_length=225)),
                ('status', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tbl_model',
            },
        ),
    ]
