# Generated by Django 3.1.4 on 2021-02-19 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_model',
            old_name='Photo',
            new_name='photo',
        ),
        migrations.RemoveField(
            model_name='tbl_model',
            name='Contact',
        ),
    ]
