# Generated by Django 3.1.4 on 2021-02-19 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20210219_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=30)),
                ('model_no', models.IntegerField()),
                ('product_name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=30)),
                ('size', models.CharField(max_length=30)),
                ('colour', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('stock', models.CharField(max_length=30)),
                ('Photo', models.CharField(max_length=225)),
                ('status', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tbl_product',
            },
        ),
    ]
