# Generated by Django 3.1.4 on 2021-02-20 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_tbl_coustomer_tbl_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=30)),
                ('coustomer_id', models.CharField(max_length=30)),
                ('product_id', models.CharField(max_length=30)),
                ('quantity', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('order_date', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tbl_order',
            },
        ),
        migrations.CreateModel(
            name='tbl_review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_id', models.CharField(max_length=30)),
                ('coustomer_id', models.CharField(max_length=30)),
                ('product_id', models.CharField(max_length=30)),
                ('reviews', models.CharField(max_length=30)),
                ('review_date', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tbl_review',
            },
        ),
    ]
