# Generated by Django 3.1.4 on 2021-02-21 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_tbl_complaint'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=30)),
                ('bank_name', models.CharField(max_length=30)),
                ('cardtype', models.CharField(max_length=30)),
                ('card_no', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('payment_date', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tbl_payment',
            },
        ),
    ]
