# Generated by Django 3.1.4 on 2021-02-21 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_tbl_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_payment',
            name='order_id',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
