# Generated by Django 3.1.4 on 2021-02-21 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_tbl_payment_order_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_account',
            old_name='stock',
            new_name='email',
        ),
        migrations.AddField(
            model_name='tbl_account',
            name='phone',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tbl_account',
            name='roll',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
