# Generated by Django 3.1.4 on 2021-02-21 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_auto_20210221_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_id', models.CharField(max_length=30)),
                ('order_id', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
                ('delivery_date', models.CharField(max_length=30)),
                ('time', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tbl_delivery',
            },
        ),
        migrations.AlterField(
            model_name='tbl_product',
            name='stock',
            field=models.IntegerField(),
        ),
    ]
