# Generated by Django 3.1.1 on 2021-03-09 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_auto_20210304_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_payment',
            name='totals',
            field=models.IntegerField(default=6, max_length=30),
            preserve_default=False,
        ),
    ]
