# Generated by Django 3.1.1 on 2021-03-09 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_tbl_payment_totals'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_payment',
            old_name='totals',
            new_name='total',
        ),
    ]
